name: Conda package

on: workflow_dispatch

#on:
#  release:
#    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish Loop Conda
        uses: Loop3D/conda-publish-action@1.0
        with:
          subdir: "conda"
          anacondatoken: ${{ secrets.CONDA_API_TOKEN }}
          platforms: "win osx linux"
